### PR TITLE
mesa: Update dependencies for Trixie

### PR DESCRIPTION
**Pull request by glneo**
Update Mesa Debian files for Trixie.

### CODE REVIEW

**Comment by jsuhaas22** [comment]
We need to add an entry in the changelog file too, for 10.01.06. They have updated the srcrev in Yocto:
https://git.ti.com/cgit/arago-project/meta-ti/tree/meta-ti-bsp/recipes-graphics/mesa/mesa-pvr_23.2.1.bb?h=10.01.06

The new srcrev gives an error while applying patches:
https://gist.github.com/jsuhaas22/481ab88d05580f30ef5b6ed4b6b7709b

**Comment by jsuhaas22** [comment]
I removed the 1st patch from the series file (the "0001-PVR..." one). And that seems to build it. (Yet to test it though.)

**Comment by glneo** [comment]
The changelog can be updated in the next PR. This one only does what should have been done when all the files from Bookworm where copied over to Trixie. This just fixes build, but doesn't update the Mesa source in any way.

**Comment by jsuhaas22** [comment]
Alright, then, LGTM.

**Review by jsuhaas22 — APPROVED** [review]

**Review by cshilwant — APPROVED** [review]

**Pull request merged**
