### PR TITLE
Builder script updates

### PR DESCRIPTION
**Pull request by glneo**
Set of patches that move us towards automated package building. Build containers and related automation scripts are next.

### CODE REVIEW

**Comment by jsuhaas22** [comment]
I checked this PR out and built ti-rpmsg-char, cryptodev-linux and ti-linux-kernel-rt for testing, in chroot environment. I was able to build the first two. However, the third throws an error:

```bash
root@debian:~/git/debian-repos# ./run.sh ti-linux-kernel-rt/
Building  ti-linux-kernel  version  09.02.00.001-rt-1
Cloning into '/root/git/debian-repos/build/sources/ti-linux-kernel'...
remote: Enumerating objects: 13322277, done.
remote: Counting objects: 100% (13322277/13322277), done.
remote: Compressing objects: 100% (1772669/1772669), done.
remote: Total 13322277 (delta 11487214), reused 13320963 (delta 11486164), pack-reused 0
Receiving objects: 100% (13322277/13322277), 2.94 GiB | 968.00 KiB/s, done.
Resolving deltas: 100% (11487214/11487214), done.
Checking objects: 100% (33554432/33554432), done.
Updating files: 100% (52224/52224), done.
Updating files: 100% (92579/92579), done.
Note: switching to '09.02.00.001-rt'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 0f8de5c40f57 Merge branch 'ti-linux-6.1.y-cicd' of git://git.ti.com/ti-linux-kernel/ti-linux-kernel into ti-rt-linux-6.1.y-cicd
I: set parameters
I: =================================================================
I: package_dir     = /usr/lib/python3/dist-packages
I: base_path       = /usr
I: base_lib_path   = /usr/lib/debmake
I: base_share_path = /usr/share/debmake
I: =================================================================
I: sanity check of parameters
I: pkg="ti-linux-kernel-09.02.00.001", ver="rt", rev="1"
I: *** start packaging in "ti-linux-kernel-09.02.00.001-rt". ***
I: provide ti-linux-kernel-09.02.00.001_rt.orig.tar.gz for non-native Debian package
I: pwd = "/root/git/debian-repos/build/bookworm/ti-linux-kernel-rt"
E: missing "ti-linux-kernel-09.02.00.001-rt.tar.gz".
root@debian:~/git/debian-repos# 
```

Do you get this as well?

**Comment by sskartheekadivi** [comment]
@glneo, any updates on this?

**Comment by sskartheekadivi** [comment]
@glneo, Ping.

**Comment by glneo** [comment]
@jsuhaas22 , I do not get that locally, not sure what is looking for that file, the kernel source should be in a file called `ti-linux-kernel_09.02.00.001-rt.orig.tar.gz`. Have you tried completely removing your build/ directory and trying again? Also what OS/version are you building from?

**Comment by sskartheekadivi** [comment]
@glneo, I started a build with your branch. Will update the status in few mins.

**Comment by jsuhaas22** [comment]
@glneo
Yes I re-tried after removing `build/` directory. But I got the same output. I also tried doing this in a new chroot environment and then in a docker container, but it gave me the same output.

I am using Debian Bookworm in chroot environment. Kernel release is 6.5.0-21-generic. I tried running builds for other packages just to make sure that there's not problem in build environment, but other packages built fine.

For running arm docker on amd64, I followed these steps: https://www.stereolabs.com/docs/docker/building-arm-container-on-x86.

**Comment by glneo** [comment]
@jsuhaas22 , I think I found the issue. Some version of debmake have an issue with the last dash in the name -rt. Since we don't really use that step, I've added a patch to remove it.

**Comment by sskartheekadivi** [comment]
@glneo, ti-linux-kernel build with these changes inside arm64 docker container is triggering oom-killer. I tried multiple times on a server with 64 cores and 250GB RAM and on a PC with 16 cores and 32GB RAM. Same observation.

Should we limit the simultaneous jobs to nproc-2 instead of nproc like we currently do? Haven't tried yet but suspecting.

BTW, I'm not facing the issue that @jsuhaas22 is facing. 
For me, make config works, but when the make Image starts, the Host PC crashes.

**Comment by jsuhaas22** [comment]
@glneo The latest commit fixes my previous issue. It goes beyond that point and starts building. 

However, like for @sskartheekadivi, it triggers oom-killer. My PC is 20 cores and 32GB RAM.

**Comment by glneo** [comment]
The memory usage does seem to be exponentially related to CPU cores, not linearly related as one would expect. I think this might be a memory leak in docker+qemu. I don't see the same when doing native docker builds on ARM64/AMD64 hardware, only with docker+qemu.

For now I guess we can limit the builds to 2 cores or so (this seems to peak at around 32GB in qemu/docker). This will make the build take a while, the alternative is to use an ARM64 VM instead of docker.

**Comment by jsuhaas22** [comment]
Great, it builds for me successfully! 

Since there are so many changes in this PR, we will merge it after the code freeze for this release.

**Comment by sskartheekadivi** [comment]
@glneo
Now as the release is done, can you rebase this PR.

**Review by sskartheekadivi — APPROVED** [review]

**Pull request merged**
